"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Play, SkipForward, Pause } from "lucide-react";

const SCENARIOS = [
    {
        id: 1,
        title: "2035: The Pivot",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop", // Skyscraper mock
        desc: "You finally automated your income. The stress lines have faded."
    },
    {
        id: 2,
        title: "2050: The Legacy",
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1974&auto=format&fit=crop", // Library mock
        desc: "Published your third book. Your grandkids are asking about the early AI days."
    },
    {
        id: 3,
        title: "2080: The Resting Place",
        image: "https://images.unsplash.com/photo-1494548162494-384bba4ab999?q=80&w=2080&auto=format&fit=crop", // Sunrise
        desc: "You look back with no regrets. You crafted the story you wanted to read."
    }
];

export function LifeSlideshow() {
    const [currentIndex, setCurrentIndex] = useState(0);
    const [isPlaying, setIsPlaying] = useState(false);

    const handlePlay = () => {
        setIsPlaying(true);
        // Mock play loop
        let i = currentIndex;
        const interval = setInterval(() => {
            i++;
            if (i >= SCENARIOS.length) {
                clearInterval(interval);
                setIsPlaying(false);
                setCurrentIndex(0);
            } else {
                setCurrentIndex(i);
            }
        }, 3000);
    };

    return (
        <div className="relative w-full h-full min-h-[400px] flex flex-col">
            <div className="absolute inset-0 bg-black">
                <AnimatePresence mode="wait">
                    <motion.div
                        key={currentIndex}
                        initial={{ opacity: 0, scale: 1.1 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 1 }}
                        className="absolute inset-0"
                    >
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                            src={SCENARIOS[currentIndex].image}
                            alt="Scenario"
                            className="w-full h-full object-cover opacity-60"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent" />
                    </motion.div>
                </AnimatePresence>
            </div>

            <div className="relative z-10 flex-1 flex flex-col justify-end p-8 text-white">
                <motion.div
                    key={currentIndex}
                    initial={{ y: 20, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.2 }}
                >
                    <div className="inline-block px-3 py-1 bg-primary/80 backdrop-blur-sm rounded-full text-xs font-bold mb-2">
                        {SCENARIOS[currentIndex].title}
                    </div>
                    <h2 className="text-3xl font-bold mb-2 max-w-2xl leading-tight">
                        {SCENARIOS[currentIndex].desc}
                    </h2>
                </motion.div>
            </div>

            {!isPlaying && (
                <div className="absolute inset-0 flex items-center justify-center z-20 bg-black/20 backdrop-blur-[2px]">
                    <button
                        onClick={handlePlay}
                        className="w-20 h-20 bg-white/10 hover:bg-white/20 border-2 border-white/50 rounded-full flex items-center justify-center backdrop-blur-md transition-all hover:scale-110 group"
                    >
                        <Play className="w-8 h-8 text-white fill-white ml-1 group-hover:scale-110 transition-transform" />
                    </button>
                    <div className="absolute bottom-8 text-white/50 text-sm font-medium">
                        Preview Generated by Nanobanana
                    </div>
                </div>
            )}
        </div>
    );
}
